export const jojoProducts = [
  [
    {
      name: 'Шницель с кремом из авокадо',
      image: require('../assets/shnitsel.png'),
      price: 50,
      count: 1,
      weight: 400,
    },
    {
      name: 'Котлета с овощным гарниром',
      image: require('../assets/kotleta.png'),
      price: 55,
      count: 1,
      weight: 400,
    },
    {
      name: 'Салат с теплым соусом',
      image: require('../assets/tepliy_salat.png'),
      price: 35,
      count: 1,
      weight: 380,
    },
    {
      name: 'Блинчики с черничным вареньем',
      image: require('../assets/blini_s_chernikoy.png'),
      price: 40,
      count: 1,
      weight: 280,
    },
    {
      name: 'Паста с овощным соусом',
      image: require('../assets/makaroni.png'),
      price: 65,
      count: 1,
      weight: 280,
    },
  ],
  [
    {
      name: 'Традиционная уха',
      image: require('../assets/uxa.png'),
      price: 35,
      count: 1,
      weight: 360,
    },
    {
      name: 'Рамен с курицей',
      image: require('../assets/ramen.png'),
      price: 50,
      count: 1,
      weight: 400,
    },
    {
      name: 'Домашний куриный бульон',
      image: require('../assets/kurinniy_bulyon.png'),
      price: 55,
      count: 1,
      weight: 310,
    },
    {
      name: 'Томатный крем-суп',
      image: require('../assets/tomatniy_sup.png'),
      price: 55,
      count: 1,
      weight: 300,
    },
    {
      name: 'Грибной крем-суп',
      image: require('../assets/gribnoy_sup.png'),
      price: 40,
      count: 1,
      weight: 300,
    },
  ],
  [
    {
      name: 'Брауни с шоколадной глазурью',
      image: require('../assets/brauni.png'),
      price: 25,
      count: 1,
      weight: 160,
    },
    {
      name: 'Панкейки с ягодами и фруктами',
      image: require('../assets/pankeyki.png'),
      price: 15,
      count: 1,
      weight: 150,
    },
    {
      name: 'Блинчики с черничным сиропом',
      image: require('../assets/blini.png'),
      price: 25,
      count: 1,
      weight: 160,
    },
    {
      name: 'Манговый чизкейк',
      image: require('../assets/chizkeyk.png'),
      price: 15,
      count: 1,
      weight: 200,
    },
    {
      name: 'Сладкий ролл с фруктами',
      image: require('../assets/rol.png'),
      price: 35,
      count: 1,
      weight: 180,
    },
  ],
];
